In [1]:
import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import os

In [2]:
display (os.getcwd())

'C:\\Users\\HP'

In [3]:
os.chdir('D:\\Movie')

In [4]:
os.getcwd()

'D:\\Movie'

In [5]:
data=pd.read_csv('movie.csv')
data.head()

Title                  Run Time Rating User Rating  \
0        Top Gun: Maverick  $170,000,000 (estimated)    8.6        187K   
1  Jurassic World Dominion        2 hours 27 minutes      6         56K   
2                  Top Gun   $15,000,000 (estimated)    6.9        380K   
3                Lightyear               $71,101,257    5.2         32K   
4               Spiderhead              not-released    5.4         23K   

                                  Genre  \
0                   ['Action', 'Drama']   
1     ['Action', 'Adventure', 'Sci-Fi']   
2                   ['Action', 'Drama']   
3  ['Animation', 'Action', 'Adventure']   
4          ['Action', 'Crime', 'Drama']   

                                            Overview  \
0  After more than thirty years of service as one...   
1  Four years after the destruction of Isla Nubla...   
2  As students at the United States Navy's elite ...   
3  While spending years attempting to return home...   
4  In the near future, convicts are offered the c...   

                                            Keywords         Director  \
0  ['fighter jet', 'sequel', 'u.s. navy', 'fighte...  Joseph Kosinski   
1  ['dinosaur', 'jurassic park', 'tyrannosaurus r...  Colin Trevorrow   
2  ['pilot', 'male camaraderie', 'u.s. navy', 'gr...       Tony Scott   
3  ['galaxy', 'spaceship', 'robot', 'rocket', 'sp...    Angus MacLane   
4  ['discover', 'medical', 'test', 'reality', 'fi...  Joseph Kosinski   

                                                Cast            Writer   year  \
0  ['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...          Jim Cash  -2022   
1  ['Colin Trevorrow', 'Derek Connolly', 'Chris P...  Emily Carmichael  -2022   
2  ['Jack Epps Jr.', 'Ehud Yonay', 'Tom Cruise', ...          Jim Cash  -1986   
3  ['Jason Headley', 'Matthew Aldrich', 'Chris Ev...     Angus MacLane  -2022   
4  ['Rhett Reese', 'Paul Wernick', 'Chris Hemswor...   George Saunders  -2022   

                 path  
0   /title/tt1745960/  
1   /title/tt8041270/  
2   /title/tt0092099/  
3  /title/tt10298810/  
4   /title/tt9783600/

In [6]:
data.dtypes

Title          object
Run Time       object
Rating         object
User Rating    object
Genre          object
Overview       object
Keywords       object
Director       object
Cast           object
Writer         object
year           object
path           object
dtype: object

In [7]:
display (data.shape)

(24402, 12)

In [8]:
selected_features = ['Title','Genre','Overview','Keywords','Cast', 'Director', 'Writer']
print(selected_features)

['Title', 'Genre', 'Overview', 'Keywords', 'Cast', 'Director', 'Writer']


In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24402 entries, 0 to 24401
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Title        24402 non-null  object
 1   Run Time     24402 non-null  object
 2   Rating       24402 non-null  object
 3   User Rating  24402 non-null  object
 4   Genre        24402 non-null  object
 5   Overview     24158 non-null  object
 6   Keywords     24402 non-null  object
 7   Director     24402 non-null  object
 8   Cast         24402 non-null  object
 9   Writer       24402 non-null  object
 10  year         23624 non-null  object
 11  path         24402 non-null  object
dtypes: object(12)
memory usage: 2.2+ MB


In [10]:
data.isna().sum()

Title            0
Run Time         0
Rating           0
User Rating      0
Genre            0
Overview       244
Keywords         0
Director         0
Cast             0
Writer           0
year           778
path             0
dtype: int64

In [11]:
data[selected_features].head()

Title                                 Genre  \
0        Top Gun: Maverick                   ['Action', 'Drama']   
1  Jurassic World Dominion     ['Action', 'Adventure', 'Sci-Fi']   
2                  Top Gun                   ['Action', 'Drama']   
3                Lightyear  ['Animation', 'Action', 'Adventure']   
4               Spiderhead          ['Action', 'Crime', 'Drama']   

                                            Overview  \
0  After more than thirty years of service as one...   
1  Four years after the destruction of Isla Nubla...   
2  As students at the United States Navy's elite ...   
3  While spending years attempting to return home...   
4  In the near future, convicts are offered the c...   

                                            Keywords  \
0  ['fighter jet', 'sequel', 'u.s. navy', 'fighte...   
1  ['dinosaur', 'jurassic park', 'tyrannosaurus r...   
2  ['pilot', 'male camaraderie', 'u.s. navy', 'gr...   
3  ['galaxy', 'spaceship', 'robot', 'rocket', 'sp...   
4  ['discover', 'medical', 'test', 'reality', 'fi...   

                                                Cast         Director  \
0  ['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...  Joseph Kosinski   
1  ['Colin Trevorrow', 'Derek Connolly', 'Chris P...  Colin Trevorrow   
2  ['Jack Epps Jr.', 'Ehud Yonay', 'Tom Cruise', ...       Tony Scott   
3  ['Jason Headley', 'Matthew Aldrich', 'Chris Ev...    Angus MacLane   
4  ['Rhett Reese', 'Paul Wernick', 'Chris Hemswor...  Joseph Kosinski   

             Writer  
0          Jim Cash  
1  Emily Carmichael  
2          Jim Cash  
3     Angus MacLane  
4   George Saunders

In [12]:
data[selected_features].isna().sum()

Title         0
Genre         0
Overview    244
Keywords      0
Cast          0
Director      0
Writer        0
dtype: int64

In [13]:
for feature in selected_features:
  data[feature] = data[feature].fillna('')
display (data.head())

Title                  Run Time Rating User Rating  \
0        Top Gun: Maverick  $170,000,000 (estimated)    8.6        187K   
1  Jurassic World Dominion        2 hours 27 minutes      6         56K   
2                  Top Gun   $15,000,000 (estimated)    6.9        380K   
3                Lightyear               $71,101,257    5.2         32K   
4               Spiderhead              not-released    5.4         23K   

                                  Genre  \
0                   ['Action', 'Drama']   
1     ['Action', 'Adventure', 'Sci-Fi']   
2                   ['Action', 'Drama']   
3  ['Animation', 'Action', 'Adventure']   
4          ['Action', 'Crime', 'Drama']   

                                            Overview  \
0  After more than thirty years of service as one...   
1  Four years after the destruction of Isla Nubla...   
2  As students at the United States Navy's elite ...   
3  While spending years attempting to return home...   
4  In the near future, convicts are offered the c...   

                                            Keywords         Director  \
0  ['fighter jet', 'sequel', 'u.s. navy', 'fighte...  Joseph Kosinski   
1  ['dinosaur', 'jurassic park', 'tyrannosaurus r...  Colin Trevorrow   
2  ['pilot', 'male camaraderie', 'u.s. navy', 'gr...       Tony Scott   
3  ['galaxy', 'spaceship', 'robot', 'rocket', 'sp...    Angus MacLane   
4  ['discover', 'medical', 'test', 'reality', 'fi...  Joseph Kosinski   

                                                Cast            Writer   year  \
0  ['Jack Epps Jr.', 'Peter Craig', 'Tom Cruise',...          Jim Cash  -2022   
1  ['Colin Trevorrow', 'Derek Connolly', 'Chris P...  Emily Carmichael  -2022   
2  ['Jack Epps Jr.', 'Ehud Yonay', 'Tom Cruise', ...          Jim Cash  -1986   
3  ['Jason Headley', 'Matthew Aldrich', 'Chris Ev...     Angus MacLane  -2022   
4  ['Rhett Reese', 'Paul Wernick', 'Chris Hemswor...   George Saunders  -2022   

                 path  
0   /title/tt1745960/  
1   /title/tt8041270/  
2   /title/tt0092099/  
3  /title/tt10298810/  
4   /title/tt9783600/

In [14]:
combined_features = data['Title']+' '+data['Genre']+' '+data['Overview']+' '+['Keywords']+' '+data['Cast']+data['Director']+data['Writer']
combined_features

0        Top Gun: Maverick ['Action', 'Drama'] After mo...
1        Jurassic World Dominion ['Action', 'Adventure'...
2        Top Gun ['Action', 'Drama'] As students at the...
3        Lightyear ['Animation', 'Action', 'Adventure']...
4        Spiderhead ['Action', 'Crime', 'Drama'] In the...
                               ...                        
24397    Delicatessen ['Comedy', 'Crime'] Post-apocalyp...
24398    Bitch Ass ['Crime', 'Horror'] A gang initiatio...
24399    Bullwhip ['Crime', 'Romance', 'Western'] In or...
24400    The Freshman ['Comedy', 'Crime'] An N.Y.C. fil...
24401    Guys and Dolls ['Comedy', 'Crime', 'Musical'] ...
Length: 24402, dtype: object

In [15]:
#Converting the text data to feature vectors
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)
display (feature_vectors.shape)
print (feature_vectors)

(24402, 90982)

  (0, 13905)	0.1433659009356546
  (0, 44748)	0.22525473983931385
  (0, 41264)	0.11011908968185793
  (0, 80954)	0.16459078035817684
  (0, 54078)	0.13475630726917479
  (0, 17221)	0.15886290516455018
  (0, 40570)	0.11176758155106288
  (0, 18680)	0.14862933897369618
  (0, 82408)	0.09617670110399468
  (0, 18234)	0.11726313009137525
  (0, 62249)	0.09143143253273261
  (0, 41365)	0.10256005209341121
  (0, 25491)	0.16665326683874832
  (0, 39792)	0.09880202111094935
  (0, 43350)	0.021639729195830272
  (0, 32947)	0.15276372255868642
  (0, 89024)	0.13211593678114963
  (0, 81413)	0.06470784092595322
  (0, 66217)	0.20148106742132466
  (0, 38464)	0.038521584813294645
  (0, 1493)	0.21648058470149514
  (0, 22534)	0.21025522255914336
  (0, 3317)	0.034571359463654756
  (0, 62791)	0.13577085537175537
  (0, 81226)	0.14017109790193544
  :	:
  (24401, 89793)	0.11383718824488923
  (24401, 24026)	0.12057523061413027
  (24401, 16580)	0.1486132879969613
  (24401, 19482)	0.1544686338278793
  (24401, 40434)	0.1199

In [16]:
#Getting the similarity scores using cosine similarity
similarity = cosine_similarity(feature_vectors)
print  (similarity )

[[1.         0.02740539 0.24308284 ... 0.00454946 0.01095966 0.02306416]
 [0.02740539 1.         0.01741563 ... 0.00534757 0.01578345 0.02169353]
 [0.24308284 0.01741563 1.         ... 0.00909713 0.02086946 0.01045162]
 ...
 [0.00454946 0.00534757 0.00909713 ... 1.         0.00506162 0.0197934 ]
 [0.01095966 0.01578345 0.02086946 ... 0.00506162 1.         0.06630982]
 [0.02306416 0.02169353 0.01045162 ... 0.0197934  0.06630982 1.        ]]


In [17]:
display(similarity.shape)

(24402, 24402)

In [18]:
#Enter the movie name to get Similarity 
movie_name = input(' Enter your favourite movie name : ')

 Enter your favourite movie name :  The Chronicles of Narnia


In [19]:
list_of_all_titles = data['Title'].tolist()
print(list_of_all_titles)

['Top Gun: Maverick', 'Jurassic World Dominion', 'Top Gun', 'Lightyear', 'Spiderhead', 'Everything Everywhere All at Once', 'Interceptor', 'Interceptor', 'Black Adam', 'The Northman', 'Thor: Love and Thunder', 'Fantastic Beasts: The Secrets of Dumbledore', 'The Unbearable Weight of Massive Talent', 'Jurassic Park', 'Doctor Strange in the Multiverse of Madness', 'No Time to Die', 'The Batman', 'Bullet Train', 'Bullet Train', 'Jurassic World', 'Jurassic World: Fallen Kingdom', 'Vikram', 'Morbius', 'The Lost City', 'Spider-Man: No Way Home', 'Last Seen Alive', 'Sonic the Hedgehog 2', 'Uncharted', 'Prey', 'Prey', 'Prey', 'Ambulance', 'Ambulance', 'The Lost World: Jurassic Park', 'Dune', 'Dune', 'Jurassic Park III', 'Star Wars', 'The Gray Man', 'Avengers: Endgame', 'The Lady of Heaven', 'Pirates of the Caribbean: The Curse of the Black Pearl', 'Eternals', 'Free Guy', 'The Matrix Resurrections', 'Mission: Impossible', 'Memory', 'Memory', 'Star Wars: Episode I - The Phantom Menace', 'The Adam

In [20]:
len(list_of_all_titles)

24402

In [21]:
#Finding the close match for the movie name given by the user
find_close_match = difflib.get_close_matches(movie_name, list_of_all_titles)
print(find_close_match)

['The Chronicles of Riddick', 'The Chronicles of Narnia: Prince Caspian', 'The Chronicles of Narnia: The Silver Chair']


In [22]:
#Display the close match
close_match = find_close_match[0]
print(close_match)

The Chronicles of Riddick


In [23]:
#Finding the index of the movie with the title
index_of_the_movie = data[data.Title == close_match].index.values[0]
print(index_of_the_movie)

672


In [24]:
#Get the similarity row for the selected index 
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.017679749666639412), (1, 0.06590946724125525), (2, 0.018296834999582883), (3, 0.022577841250373456), (4, 0.015872298129440382), (5, 0.03154278401957171), (6, 0.02281794743585984), (7, 0.027772491182940253), (8, 0.02428468921092468), (9, 0.022483764893032783), (10, 0.016754872116769435), (11, 0.05181670811627856), (12, 0.008090344595855519), (13, 0.04172917379138627), (14, 0.04690638761123151), (15, 0.019682224740646573), (16, 0.01234080782179531), (17, 0.02729821789270765), (18, 0.018337911188724118), (19, 0.02585368505097386), (20, 0.02463803152930216), (21, 0.008890554328393314), (22, 0.024809621205894267), (23, 0.02624354888200184), (24, 0.007396056377905963), (25, 0.030362323022619295), (26, 0.024871308558315416), (27, 0.010826640836478675), (28, 0.028355784147304032), (29, 0.020382765440607832), (30, 0.020715049948277664), (31, 0.007412073233554579), (32, 0.013089485067984182), (33, 0.041318497425537226), (34, 0.011008361287641781), (35, 0.06631380293172076), (36, 0.0201904

In [25]:
#Length of Similarity Score 
len(similarity_score)

24402

In [26]:
#Sorting the movies based on their similarity score
sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_movies)

[(672, 1.0), (1830, 0.49691840762217365), (635, 0.47931994940281497), (798, 0.37488297403461085), (23848, 0.33059722298914995), (76, 0.1839337375533284), (6013, 0.18128749655580964), (10637, 0.16977950709342707), (2917, 0.14815351443876867), (21495, 0.14710858184356948), (22397, 0.14693134320864545), (11613, 0.1446650971334545), (758, 0.1438551180992171), (884, 0.14358340277889511), (440, 0.13983985760769962), (8787, 0.1369665626585943), (12507, 0.13603530332865912), (979, 0.13510547359211542), (1781, 0.13366873482125977), (202, 0.13246522854713266), (432, 0.13080581307634315), (466, 0.1287014600031947), (986, 0.12505862072085774), (831, 0.1173127153434548), (5449, 0.11483994670311422), (14864, 0.11212669315390761), (9973, 0.10827306918258803), (1096, 0.10740180599817802), (15289, 0.105917597437892), (2105, 0.09766179768603252), (19706, 0.09524540500963842), (8472, 0.08965417973734437), (15910, 0.08752854488167523), (19478, 0.08747570590089684), (1668, 0.08741071583513559), (2216, 0.08

In [27]:
#Print the name of similar movies based on the index – Top 30 
print('Movies suggested for you : \n')
i = 1
for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index =data[data.index==index]['Title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

Movies suggested for you : 

1 . The Chronicles of Riddick
2 . Furya
3 . Riddick
4 . Pitch Black
5 . Strays
6 . Guardians of the Galaxy
7 . The Clinic
8 . The Fly II
9 . Muscle
10 . The Arrival
11 . The Silent Scream
12 . Find Me Guilty
13 . Bloodshot
14 . The Last Witch Hunter
15 . The Fate of the Furious
16 . A Perfect Getaway
17 . Knockaround Guys
18 . xXx
19 . A Man Apart
20 . The Fast and the Furious
21 . Fast & Furious
22 . Fast Five
23 . Babylon A.D.
24 . xXx: Return of Xander Cage
25 . Prime Target
26 . Mrs. Henderson Presents
27 . Boiler Room
28 . The Pacifier
29 . Allelujah
